name: Buildlight

on:
  workflow_run:
    workflows:
      - rspec
      - standardrb
    branches:
      - main

jobs:
  buildlight:
    runs-on: ubuntu-latest
    steps:
      - uses: collectiveidea/buildlight@main
