name: rspec

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      COVERAGE: true

    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        cache-version: 1

    - name: Setup Code Climate Test Reporter
      run: |
        sudo curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        sudo chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run RSpec
      run: bundle exec rake spec

    - name: Coverage Report
      run: |
        ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
